spring:
  application.name: money-raven
  jpa.hibernate.ddl-auto: validate
  h2.console.enabled: true
  profile: WINTER_HERE

ironbank:
   lstReturningDepts:
      - Ланистеры
      - Мевины
raven:
  turn-on: true
  where:
    - Мейрин

